package com.xust.easyschool.dao;

import com.xust.easyschool.bean.comsumer;
import com.xust.easyschool.bean.comsumerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface comsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    long countByExample(comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int deleteByExample(comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int deleteByPrimaryKey(Integer consumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int insert(comsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int insertSelective(comsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    List<comsumer> selectByExampleWithBLOBs(comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    List<comsumer> selectByExample(comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    comsumer selectByPrimaryKey(Integer consumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") comsumer record, @Param("example") comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") comsumer record, @Param("example") comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByExample(@Param("record") comsumer record, @Param("example") comsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByPrimaryKeySelective(comsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(comsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByPrimaryKey(comsumer record);
}