package com.xust.easyschool.dao;

import com.xust.easyschool.bean.login;
import com.xust.easyschool.bean.loginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface loginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    long countByExample(loginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int deleteByExample(loginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int insert(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int insertSelective(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    List<login> selectByExample(loginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    login selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") login record, @Param("example") loginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByExample(@Param("record") login record, @Param("example") loginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByPrimaryKeySelective(login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    int updateByPrimaryKey(login record);
}