package com.xust.easyschool.bean;

import java.util.Date;

public class comsumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_id
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private Integer consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_name
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_sex
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_nickname
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_number
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private Integer consumerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_school
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_institute
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerInstitute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_major
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_grade
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_identity
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String consumerIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.attention
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private Integer attention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.fan
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private Integer fan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.create_at
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.update_at
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.deleted
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private String deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.consumer_head
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    private byte[] consumerHead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_id
     *
     * @return the value of consumer.consumer_id
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Integer getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_id
     *
     * @param consumerId the value for consumer.consumer_id
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerId(Integer consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_name
     *
     * @return the value of consumer.consumer_name
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_name
     *
     * @param consumerName the value for consumer.consumer_name
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerName(String consumerName) {
        this.consumerName = consumerName == null ? null : consumerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_sex
     *
     * @return the value of consumer.consumer_sex
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerSex() {
        return consumerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_sex
     *
     * @param consumerSex the value for consumer.consumer_sex
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerSex(String consumerSex) {
        this.consumerSex = consumerSex == null ? null : consumerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_nickname
     *
     * @return the value of consumer.consumer_nickname
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerNickname() {
        return consumerNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_nickname
     *
     * @param consumerNickname the value for consumer.consumer_nickname
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerNickname(String consumerNickname) {
        this.consumerNickname = consumerNickname == null ? null : consumerNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_number
     *
     * @return the value of consumer.consumer_number
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Integer getConsumerNumber() {
        return consumerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_number
     *
     * @param consumerNumber the value for consumer.consumer_number
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerNumber(Integer consumerNumber) {
        this.consumerNumber = consumerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_school
     *
     * @return the value of consumer.consumer_school
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerSchool() {
        return consumerSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_school
     *
     * @param consumerSchool the value for consumer.consumer_school
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerSchool(String consumerSchool) {
        this.consumerSchool = consumerSchool == null ? null : consumerSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_institute
     *
     * @return the value of consumer.consumer_institute
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerInstitute() {
        return consumerInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_institute
     *
     * @param consumerInstitute the value for consumer.consumer_institute
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerInstitute(String consumerInstitute) {
        this.consumerInstitute = consumerInstitute == null ? null : consumerInstitute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_major
     *
     * @return the value of consumer.consumer_major
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerMajor() {
        return consumerMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_major
     *
     * @param consumerMajor the value for consumer.consumer_major
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerMajor(String consumerMajor) {
        this.consumerMajor = consumerMajor == null ? null : consumerMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_grade
     *
     * @return the value of consumer.consumer_grade
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerGrade() {
        return consumerGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_grade
     *
     * @param consumerGrade the value for consumer.consumer_grade
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerGrade(String consumerGrade) {
        this.consumerGrade = consumerGrade == null ? null : consumerGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_identity
     *
     * @return the value of consumer.consumer_identity
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getConsumerIdentity() {
        return consumerIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_identity
     *
     * @param consumerIdentity the value for consumer.consumer_identity
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerIdentity(String consumerIdentity) {
        this.consumerIdentity = consumerIdentity == null ? null : consumerIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.attention
     *
     * @return the value of consumer.attention
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Integer getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.attention
     *
     * @param attention the value for consumer.attention
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setAttention(Integer attention) {
        this.attention = attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.fan
     *
     * @return the value of consumer.fan
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Integer getFan() {
        return fan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.fan
     *
     * @param fan the value for consumer.fan
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setFan(Integer fan) {
        this.fan = fan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.create_at
     *
     * @return the value of consumer.create_at
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.create_at
     *
     * @param createAt the value for consumer.create_at
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.update_at
     *
     * @return the value of consumer.update_at
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.update_at
     *
     * @param updateAt the value for consumer.update_at
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.deleted
     *
     * @return the value of consumer.deleted
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.deleted
     *
     * @param deleted the value for consumer.deleted
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.consumer_head
     *
     * @return the value of consumer.consumer_head
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public byte[] getConsumerHead() {
        return consumerHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.consumer_head
     *
     * @param consumerHead the value for consumer.consumer_head
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setConsumerHead(byte[] consumerHead) {
        this.consumerHead = consumerHead;
    }
}