package com.xust.easyschool.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class comsumerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public comsumerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConsumerIdIsNull() {
            addCriterion("consumer_id is null");
            return (Criteria) this;
        }

        public Criteria andConsumerIdIsNotNull() {
            addCriterion("consumer_id is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerIdEqualTo(Integer value) {
            addCriterion("consumer_id =", value, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdNotEqualTo(Integer value) {
            addCriterion("consumer_id <>", value, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdGreaterThan(Integer value) {
            addCriterion("consumer_id >", value, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("consumer_id >=", value, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdLessThan(Integer value) {
            addCriterion("consumer_id <", value, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdLessThanOrEqualTo(Integer value) {
            addCriterion("consumer_id <=", value, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdIn(List<Integer> values) {
            addCriterion("consumer_id in", values, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdNotIn(List<Integer> values) {
            addCriterion("consumer_id not in", values, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdBetween(Integer value1, Integer value2) {
            addCriterion("consumer_id between", value1, value2, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("consumer_id not between", value1, value2, "consumerId");
            return (Criteria) this;
        }

        public Criteria andConsumerNameIsNull() {
            addCriterion("consumer_name is null");
            return (Criteria) this;
        }

        public Criteria andConsumerNameIsNotNull() {
            addCriterion("consumer_name is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerNameEqualTo(String value) {
            addCriterion("consumer_name =", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameNotEqualTo(String value) {
            addCriterion("consumer_name <>", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameGreaterThan(String value) {
            addCriterion("consumer_name >", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_name >=", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameLessThan(String value) {
            addCriterion("consumer_name <", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameLessThanOrEqualTo(String value) {
            addCriterion("consumer_name <=", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameLike(String value) {
            addCriterion("consumer_name like", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameNotLike(String value) {
            addCriterion("consumer_name not like", value, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameIn(List<String> values) {
            addCriterion("consumer_name in", values, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameNotIn(List<String> values) {
            addCriterion("consumer_name not in", values, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameBetween(String value1, String value2) {
            addCriterion("consumer_name between", value1, value2, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerNameNotBetween(String value1, String value2) {
            addCriterion("consumer_name not between", value1, value2, "consumerName");
            return (Criteria) this;
        }

        public Criteria andConsumerSexIsNull() {
            addCriterion("consumer_sex is null");
            return (Criteria) this;
        }

        public Criteria andConsumerSexIsNotNull() {
            addCriterion("consumer_sex is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerSexEqualTo(String value) {
            addCriterion("consumer_sex =", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexNotEqualTo(String value) {
            addCriterion("consumer_sex <>", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexGreaterThan(String value) {
            addCriterion("consumer_sex >", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_sex >=", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexLessThan(String value) {
            addCriterion("consumer_sex <", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexLessThanOrEqualTo(String value) {
            addCriterion("consumer_sex <=", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexLike(String value) {
            addCriterion("consumer_sex like", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexNotLike(String value) {
            addCriterion("consumer_sex not like", value, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexIn(List<String> values) {
            addCriterion("consumer_sex in", values, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexNotIn(List<String> values) {
            addCriterion("consumer_sex not in", values, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexBetween(String value1, String value2) {
            addCriterion("consumer_sex between", value1, value2, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerSexNotBetween(String value1, String value2) {
            addCriterion("consumer_sex not between", value1, value2, "consumerSex");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameIsNull() {
            addCriterion("consumer_nickname is null");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameIsNotNull() {
            addCriterion("consumer_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameEqualTo(String value) {
            addCriterion("consumer_nickname =", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameNotEqualTo(String value) {
            addCriterion("consumer_nickname <>", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameGreaterThan(String value) {
            addCriterion("consumer_nickname >", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_nickname >=", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameLessThan(String value) {
            addCriterion("consumer_nickname <", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameLessThanOrEqualTo(String value) {
            addCriterion("consumer_nickname <=", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameLike(String value) {
            addCriterion("consumer_nickname like", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameNotLike(String value) {
            addCriterion("consumer_nickname not like", value, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameIn(List<String> values) {
            addCriterion("consumer_nickname in", values, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameNotIn(List<String> values) {
            addCriterion("consumer_nickname not in", values, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameBetween(String value1, String value2) {
            addCriterion("consumer_nickname between", value1, value2, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNicknameNotBetween(String value1, String value2) {
            addCriterion("consumer_nickname not between", value1, value2, "consumerNickname");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberIsNull() {
            addCriterion("consumer_number is null");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberIsNotNull() {
            addCriterion("consumer_number is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberEqualTo(Integer value) {
            addCriterion("consumer_number =", value, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberNotEqualTo(Integer value) {
            addCriterion("consumer_number <>", value, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberGreaterThan(Integer value) {
            addCriterion("consumer_number >", value, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("consumer_number >=", value, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberLessThan(Integer value) {
            addCriterion("consumer_number <", value, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberLessThanOrEqualTo(Integer value) {
            addCriterion("consumer_number <=", value, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberIn(List<Integer> values) {
            addCriterion("consumer_number in", values, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberNotIn(List<Integer> values) {
            addCriterion("consumer_number not in", values, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberBetween(Integer value1, Integer value2) {
            addCriterion("consumer_number between", value1, value2, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("consumer_number not between", value1, value2, "consumerNumber");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolIsNull() {
            addCriterion("consumer_school is null");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolIsNotNull() {
            addCriterion("consumer_school is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolEqualTo(String value) {
            addCriterion("consumer_school =", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolNotEqualTo(String value) {
            addCriterion("consumer_school <>", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolGreaterThan(String value) {
            addCriterion("consumer_school >", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_school >=", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolLessThan(String value) {
            addCriterion("consumer_school <", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolLessThanOrEqualTo(String value) {
            addCriterion("consumer_school <=", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolLike(String value) {
            addCriterion("consumer_school like", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolNotLike(String value) {
            addCriterion("consumer_school not like", value, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolIn(List<String> values) {
            addCriterion("consumer_school in", values, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolNotIn(List<String> values) {
            addCriterion("consumer_school not in", values, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolBetween(String value1, String value2) {
            addCriterion("consumer_school between", value1, value2, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerSchoolNotBetween(String value1, String value2) {
            addCriterion("consumer_school not between", value1, value2, "consumerSchool");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteIsNull() {
            addCriterion("consumer_institute is null");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteIsNotNull() {
            addCriterion("consumer_institute is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteEqualTo(String value) {
            addCriterion("consumer_institute =", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteNotEqualTo(String value) {
            addCriterion("consumer_institute <>", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteGreaterThan(String value) {
            addCriterion("consumer_institute >", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_institute >=", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteLessThan(String value) {
            addCriterion("consumer_institute <", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteLessThanOrEqualTo(String value) {
            addCriterion("consumer_institute <=", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteLike(String value) {
            addCriterion("consumer_institute like", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteNotLike(String value) {
            addCriterion("consumer_institute not like", value, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteIn(List<String> values) {
            addCriterion("consumer_institute in", values, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteNotIn(List<String> values) {
            addCriterion("consumer_institute not in", values, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteBetween(String value1, String value2) {
            addCriterion("consumer_institute between", value1, value2, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerInstituteNotBetween(String value1, String value2) {
            addCriterion("consumer_institute not between", value1, value2, "consumerInstitute");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorIsNull() {
            addCriterion("consumer_major is null");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorIsNotNull() {
            addCriterion("consumer_major is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorEqualTo(String value) {
            addCriterion("consumer_major =", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorNotEqualTo(String value) {
            addCriterion("consumer_major <>", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorGreaterThan(String value) {
            addCriterion("consumer_major >", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_major >=", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorLessThan(String value) {
            addCriterion("consumer_major <", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorLessThanOrEqualTo(String value) {
            addCriterion("consumer_major <=", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorLike(String value) {
            addCriterion("consumer_major like", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorNotLike(String value) {
            addCriterion("consumer_major not like", value, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorIn(List<String> values) {
            addCriterion("consumer_major in", values, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorNotIn(List<String> values) {
            addCriterion("consumer_major not in", values, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorBetween(String value1, String value2) {
            addCriterion("consumer_major between", value1, value2, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerMajorNotBetween(String value1, String value2) {
            addCriterion("consumer_major not between", value1, value2, "consumerMajor");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeIsNull() {
            addCriterion("consumer_grade is null");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeIsNotNull() {
            addCriterion("consumer_grade is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeEqualTo(String value) {
            addCriterion("consumer_grade =", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeNotEqualTo(String value) {
            addCriterion("consumer_grade <>", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeGreaterThan(String value) {
            addCriterion("consumer_grade >", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_grade >=", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeLessThan(String value) {
            addCriterion("consumer_grade <", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeLessThanOrEqualTo(String value) {
            addCriterion("consumer_grade <=", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeLike(String value) {
            addCriterion("consumer_grade like", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeNotLike(String value) {
            addCriterion("consumer_grade not like", value, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeIn(List<String> values) {
            addCriterion("consumer_grade in", values, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeNotIn(List<String> values) {
            addCriterion("consumer_grade not in", values, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeBetween(String value1, String value2) {
            addCriterion("consumer_grade between", value1, value2, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerGradeNotBetween(String value1, String value2) {
            addCriterion("consumer_grade not between", value1, value2, "consumerGrade");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityIsNull() {
            addCriterion("consumer_identity is null");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityIsNotNull() {
            addCriterion("consumer_identity is not null");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityEqualTo(String value) {
            addCriterion("consumer_identity =", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityNotEqualTo(String value) {
            addCriterion("consumer_identity <>", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityGreaterThan(String value) {
            addCriterion("consumer_identity >", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("consumer_identity >=", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityLessThan(String value) {
            addCriterion("consumer_identity <", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityLessThanOrEqualTo(String value) {
            addCriterion("consumer_identity <=", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityLike(String value) {
            addCriterion("consumer_identity like", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityNotLike(String value) {
            addCriterion("consumer_identity not like", value, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityIn(List<String> values) {
            addCriterion("consumer_identity in", values, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityNotIn(List<String> values) {
            addCriterion("consumer_identity not in", values, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityBetween(String value1, String value2) {
            addCriterion("consumer_identity between", value1, value2, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andConsumerIdentityNotBetween(String value1, String value2) {
            addCriterion("consumer_identity not between", value1, value2, "consumerIdentity");
            return (Criteria) this;
        }

        public Criteria andAttentionIsNull() {
            addCriterion("attention is null");
            return (Criteria) this;
        }

        public Criteria andAttentionIsNotNull() {
            addCriterion("attention is not null");
            return (Criteria) this;
        }

        public Criteria andAttentionEqualTo(Integer value) {
            addCriterion("attention =", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotEqualTo(Integer value) {
            addCriterion("attention <>", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionGreaterThan(Integer value) {
            addCriterion("attention >", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionGreaterThanOrEqualTo(Integer value) {
            addCriterion("attention >=", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLessThan(Integer value) {
            addCriterion("attention <", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLessThanOrEqualTo(Integer value) {
            addCriterion("attention <=", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionIn(List<Integer> values) {
            addCriterion("attention in", values, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotIn(List<Integer> values) {
            addCriterion("attention not in", values, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionBetween(Integer value1, Integer value2) {
            addCriterion("attention between", value1, value2, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotBetween(Integer value1, Integer value2) {
            addCriterion("attention not between", value1, value2, "attention");
            return (Criteria) this;
        }

        public Criteria andFanIsNull() {
            addCriterion("fan is null");
            return (Criteria) this;
        }

        public Criteria andFanIsNotNull() {
            addCriterion("fan is not null");
            return (Criteria) this;
        }

        public Criteria andFanEqualTo(Integer value) {
            addCriterion("fan =", value, "fan");
            return (Criteria) this;
        }

        public Criteria andFanNotEqualTo(Integer value) {
            addCriterion("fan <>", value, "fan");
            return (Criteria) this;
        }

        public Criteria andFanGreaterThan(Integer value) {
            addCriterion("fan >", value, "fan");
            return (Criteria) this;
        }

        public Criteria andFanGreaterThanOrEqualTo(Integer value) {
            addCriterion("fan >=", value, "fan");
            return (Criteria) this;
        }

        public Criteria andFanLessThan(Integer value) {
            addCriterion("fan <", value, "fan");
            return (Criteria) this;
        }

        public Criteria andFanLessThanOrEqualTo(Integer value) {
            addCriterion("fan <=", value, "fan");
            return (Criteria) this;
        }

        public Criteria andFanIn(List<Integer> values) {
            addCriterion("fan in", values, "fan");
            return (Criteria) this;
        }

        public Criteria andFanNotIn(List<Integer> values) {
            addCriterion("fan not in", values, "fan");
            return (Criteria) this;
        }

        public Criteria andFanBetween(Integer value1, Integer value2) {
            addCriterion("fan between", value1, value2, "fan");
            return (Criteria) this;
        }

        public Criteria andFanNotBetween(Integer value1, Integer value2) {
            addCriterion("fan not between", value1, value2, "fan");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(String value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(String value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(String value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(String value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(String value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLike(String value) {
            addCriterion("deleted like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotLike(String value) {
            addCriterion("deleted not like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<String> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<String> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(String value1, String value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(String value1, String value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consumer
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 19 22:16:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consumer
     *
     * @mbg.generated Thu Apr 19 22:16:31 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}