package com.xust.easyschool.bean;

import java.util.Date;

public class hobby {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.hobby_id
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    private Integer hobbyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.hobby_content
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    private String hobbyContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.consumer_number
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    private Integer consumerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.create_at
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.update_at
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.deleted
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.hobby_id
     *
     * @return the value of hobby.hobby_id
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public Integer getHobbyId() {
        return hobbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.hobby_id
     *
     * @param hobbyId the value for hobby.hobby_id
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public void setHobbyId(Integer hobbyId) {
        this.hobbyId = hobbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.hobby_content
     *
     * @return the value of hobby.hobby_content
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public String getHobbyContent() {
        return hobbyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.hobby_content
     *
     * @param hobbyContent the value for hobby.hobby_content
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public void setHobbyContent(String hobbyContent) {
        this.hobbyContent = hobbyContent == null ? null : hobbyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.consumer_number
     *
     * @return the value of hobby.consumer_number
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public Integer getConsumerNumber() {
        return consumerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.consumer_number
     *
     * @param consumerNumber the value for hobby.consumer_number
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public void setConsumerNumber(Integer consumerNumber) {
        this.consumerNumber = consumerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.create_at
     *
     * @return the value of hobby.create_at
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.create_at
     *
     * @param createAt the value for hobby.create_at
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.update_at
     *
     * @return the value of hobby.update_at
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.update_at
     *
     * @param updateAt the value for hobby.update_at
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.deleted
     *
     * @return the value of hobby.deleted
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.deleted
     *
     * @param deleted the value for hobby.deleted
     *
     * @mbg.generated Sat Apr 21 22:40:36 CST 2018
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}